/*
Copyright (C) 1997-2001 Id Software, Inc.

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  

See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

*/
// G:\quake2\baseq2\models/monsters/shambler

// This file generated by ModelGen - Do NOT Modify

#define FRAME_attak101        	36
#define FRAME_attak102        	37
#define FRAME_attak103        	38
#define FRAME_attak104        	39
#define FRAME_attak105        	40
#define FRAME_attak106        	41
#define FRAME_attak107        	42
#define FRAME_attak108        	43
#define FRAME_attak109        	44
#define FRAME_attak110        	45
#define FRAME_attak111        	46
#define FRAME_attak112        	47
#define FRAME_attak201        	48
#define FRAME_attak202        	49
#define FRAME_attak203        	50
#define FRAME_attak204        	51
#define FRAME_attak205        	52
#define FRAME_attak206        	53
#define FRAME_attak207        	54
#define FRAME_attak208        	55
#define FRAME_attak301        	56
#define FRAME_attak302        	57
#define FRAME_attak303        	58
#define FRAME_attak304        	60
#define FRAME_attak305        	61
#define FRAME_attak306        	62
#define FRAME_attak307        	63
#define FRAME_attak308        	64
#define FRAME_attak309        	65
#define FRAME_attak401        	66
#define FRAME_attak402        	67
#define FRAME_attak403        	68
#define FRAME_attak404        	69
#define FRAME_attak405        	70
#define FRAME_attak406        	71
#define FRAME_attak407        	72
#define FRAME_attak408        	73
#define FRAME_pain101         	74
#define FRAME_pain102         	75
#define FRAME_pain103         	76
#define FRAME_pain104         	77
#define FRAME_pain201         	78
#define FRAME_pain202         	79
#define FRAME_pain203         	80
#define FRAME_pain204         	81
#define FRAME_pain205         	82
#define FRAME_pain206         	83
#define FRAME_run01           	30
#define FRAME_run02           	31
#define FRAME_run03           	32
#define FRAME_run04           	33
#define FRAME_run05           	34
#define FRAME_run06           	35
#define FRAME_stand101        	1
#define FRAME_stand102        	2
#define FRAME_stand103        	3
#define FRAME_stand104        	4
#define FRAME_stand105        	5
#define FRAME_stand106        	6
#define FRAME_stand107        	7
#define FRAME_stand108        	8
#define FRAME_stand109        	9
#define FRAME_stand110        	10
#define FRAME_stand111        	11
#define FRAME_stand112        	12
#define FRAME_stand113        	13
#define FRAME_stand114        	14
#define FRAME_stand115        	15
#define FRAME_stand116        	16
#define FRAME_walk101         	17
#define FRAME_walk102         	18
#define FRAME_walk103         	19
#define FRAME_walk104         	20
#define FRAME_walk105         	21
#define FRAME_walk106         	22
#define FRAME_walk107         	23
#define FRAME_walk108         	24
#define FRAME_walk109         	25
#define FRAME_walk110         	26
#define FRAME_walk111         	27
#define FRAME_walk112         	28
#define FRAME_walk113         	29
#define FRAME_death101        	84
#define FRAME_death102        	85
#define FRAME_death103        	86
#define FRAME_death104        	87
#define FRAME_death105        	88
#define FRAME_death106        	89
#define FRAME_death107        	90
#define FRAME_death108        	91
#define FRAME_death109        	92
#define FRAME_death110        	93
#define FRAME_death111        	94

#define MODEL_SCALE		1.000000
